USE SUCOS;

ALTER TABLE ITENS_VENDA RENAME COLUMN QUANTIDDE TO QUANTIDADE;

ALTER TABLE ITENS_VENDA ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS (COD_PRODUTO);

ALTER TABLE VENDAS RENAME NOTAS;

ALTER TABLE ITENS_VENDA RENAME ITENS_NOTA;