CREATE DATABASE SUCOS;

USE SUCOS;

CREATE TABLE PRODUTOS (
	COD_PRODUTO INT NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(100),
	SABOR varchar(50),
    TAMANHO varchar(50),
    EMBALAGEM varchar(50),
    PRECO DOUBLE
);

CREATE TABLE VENDEDORES (
	MATRICULA INT NOT NULL PRIMARY KEY,
    NOME varchar(50),
    BAIRRO varchar(50),
    COMISSAO DOUBLE,
    DT_ADMISSAO DATE,
    FERIAS BOOLEAN
);

CREATE TABLE CLIENTES (
	CPF VARCHAR(11) NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    ENDERECO VARCHAR(100),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50), 
    ESTADO VARCHAR(2),
    CEP INT,
    DT_NASCIMENTO DATE,
    SEXO VARCHAR(1),
    LIMITE_CREDITO DOUBLE,
    VOLUME_COMPRA DOUBLE,
    PRIMEIRA_COMPRA DOUBLE
);

CREATE TABLE VENDAS (
	NUM_NOTA INT NOT NULL PRIMARY KEY,
    DT_VENDA DATE,
    CPF VARCHAR(11),
    MATRICULA INT,
    IMPOSTO DOUBLE,
    FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF),
    FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA)
);

CREATE TABLE ITENS_VENDA (
	NUM_NOTA INT NOT NULL PRIMARY KEY,
    COD_PRODUTO INT,
    QUANTIDDE INT,
    PRECO DOUBLE,
    FOREIGN KEY (NUM_NOTA) REFERENCES VENDAS (NUM_NOTA)
);